//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuscaminasVentana.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puntuacione
    {
        public Puntuacione(int score, string player)
        {
            this.Puntuacion = score;
            this.Jugador = player;
        }
        public int Id { get; set; }
        public Nullable<int> Puntuacion { get; set; }
        public string Jugador { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
